# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")

    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/98c6075c-7f42-49ec-91a0-8085d0251230";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4A35-6CEB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp129s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp130s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


## Legion Audio

# hardware.firmware = [
#   (pkgs.runCommand "legion-audio-patch" {
#     src = ./aw88399_acf.bin;
#   } ''
#     mkdir -p $out/lib/firmware
#     cp -f $src $out/lib/firmware/aw88399_acf.bin
#   '')
# ];
#
# boot.kernelPatches = [
#   {
#     name = "16iax10h-audio-linux-6.18";
#     patch = ./16iax10h-audio-linux-6.18.patch;
#     structuredExtraConfig = with lib.kernel; {
#       SND_HDA_SCODEC_AW88399 = module;
#       SND_HDA_SCODEC_AW88399_I2C = module;
#       SND_SOC_AW88399 = module;
#       SND_SOC_SOF_INTEL_TOPLEVEL = yes;
#       SND_SOC_SOF_INTEL_COMMON = module;
#       SND_SOC_SOF_INTEL_MTL = module;
#       SND_SOC_SOF_INTEL_LNL = module;
#     };
#   }
# ];



}
