general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 60
    on-timeout = hyproled
    on-resume = hyproledo
}

listener {
    timeout = 180
    on-timeout = hyprlock
}


